version: '3.8'

services:
  postgres:
    container_name: kufatech_postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kufatech_dev
    ports:
      - "5000:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: kufatech_redis
    image: redis:7-alpine
    command: redis-server --requirepass ""
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: kufatech_api
    build:
      context: .
    environment:
      - CONFIG_FILE=/app/config/config.dev.yaml
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  kufatech_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 